load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "starlark_lsp",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg=rust_nightly",
    ],
    deps = [
        "//gazebo/dupe:dupe",
        "//starlark-rust/starlark:starlark",
        "//starlark-rust/starlark_syntax:starlark_syntax",
        "//third-party/rust:derivative",
        "//third-party/rust:derive_more",
        "//third-party/rust:itertools",
        "//third-party/rust:lsp-server",
        "//third-party/rust:lsp-types",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:tower-lsp-server",
    ],
)
