load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_subscription_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_subscription_proto.proto",
    deps = [
        "//allocative/allocative:allocative",
        "//third-party/rust:derive_more",
        "//third-party/rust:serde",
    ],
)

proto_srcs(
    name = "buck2_subscription_proto.proto",
    srcs = ["subscription.proto"],
    visibility = ["PUBLIC"],
)

export_file(
    name = "subscription.proto",
    visibility = ["PUBLIC"],
)
