[package]
name = "yak_validation"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
async-trait.workspace = true
derivative.workspace = true
derive_more.workspace = true
dice.workspace = true
dice_error.workspace = true
dupe.workspace = true
pagable.workspace = true
serde.workspace = true
serde_json.workspace = true
yak_artifact.workspace = true
yak_build_api.workspace = true
yak_core.workspace = true
yak_error.workspace = true
yak_execute.workspace = true
yak_fs.workspace = true

[lints]
workspace = true
