load("//build_defs:rust.bzl", "rust_test")

rust_test(
    name = "strong_hash_tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//gazebo/strong_hash:strong_hash",
        "//third-party/rust:blake3",
    ],
)
