load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_configured",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_build_api:buck2_build_api",
        "//app/buck2_build_signals:buck2_build_signals",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_node:buck2_node",
        "//app/buck2_util:buck2_util",
        "//dice/dice:dice",
        "//dice/dice_futures:dice_futures",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//pagable:pagable",
        "//starlark-rust/starlark_map:starlark_map",
        "//third-party/rust:async-trait",
        "//third-party/rust:derive_more",
        "//third-party/rust:futures",
        "//third-party/rust:itertools",
        "//third-party/rust:ref-cast",
    ],
)
