load("//build_defs:rust.bzl", "rust_test")

rust_test(
    name = "buck2_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//app/buck2_build_api:buck2_build_api",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_interpreter:buck2_interpreter",
        "//app/buck2_interpreter_for_build:buck2_interpreter_for_build",
        "//app/buck2_node:buck2_node",
        "//app/buck2_transition:buck2_transition",
        "//app/buck2_util:buck2_util",
        "//dice/dice:dice",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//starlark-rust/starlark:starlark",
        "//third-party/rust:ctor",
        "//third-party/rust:futures",
        "//third-party/rust:indoc",
        "//third-party/rust:serde_json",
        "//third-party/rust:tokio",
    ],
)
