load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "gazebo",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    features = [
        "str_pattern_extensions",
    ],
    deps = [
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo_derive:gazebo_derive",
    ],
)
