load("//build_defs:rust.bzl", "rust_test")

filegroup(
    name = "tests",
    srcs = glob([
        "src/**/*.golden",
        "src/**",
    ]),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "buck2_error_tests",
    srcs = glob(["src/**/*.rs"]),
    env = {
        # Some of our tests include testcase files relative to CARGO_MANIFEST_DIR.
        # This is a hack that allows both `cargo test` and `buck test` to work.
        "CARGO_MANIFEST_DIR": "$(location :tests)",
    },
    deps = [
        "//app/buck2_error:buck2_error",
        "//app/buck2_util:buck2_util",
        "//starlark-rust/starlark:starlark",
        "//third-party/rust:anyhow",
    ],
)
