load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

command_alias(
    name = "protoc",
    platform_exe = {
        "linux": "prelude//toolchains/android/third-party:protoc-linux-x86_64",
        "macos": "prelude//toolchains/android/third-party:protoc-osx-x86_64",
        "windows": "prelude//toolchains/android/third-party:protoc-windows-x86_64",
    },
    visibility = ["PUBLIC"],
)

command_alias(
    name = "gen-grpc",
    platform_exe = {
        "linux": "prelude//toolchains/android/third-party:protoc-gen-grpc-java-linux-x86_64",
        "macos": "prelude//toolchains/android/third-party:protoc-gen-grpc-java-osx-x86_64",
    },
    visibility = ["PUBLIC"],
)

alias(
    name = "gen-grpc-windows",
    actual = "prelude//toolchains/android/third-party:protoc-gen-grpc-java-windows-x86_64",
    visibility = ["PUBLIC"],
)
