[package]
name = "yak_fs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
compact_str.workspace = true
derive_more.workspace = true
dunce.workspace = true
dupe.workspace = true
gazebo.workspace = true
memchr.workspace = true
pagable.workspace = true
ref-cast.workspace = true
serde.workspace = true
smallvec.workspace = true
strong_hash.workspace = true
tokio.workspace = true
yak_env.workspace = true
yak_error.workspace = true
yak_util.workspace = true

[dev-dependencies]
assert_matches.workspace = true
serde_json.workspace = true
tempfile.workspace = true
yak_hash.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
nix.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true
nix.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
common-path.workspace = true
windows-sys.workspace = true

[lints]
workspace = true
