load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_wrapper_common",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_error:buck2_error",
        "//app/buck2_hash:buck2_hash",
        "//gazebo/dupe:dupe",
        "//third-party/rust:derive_more",
        "//third-party/rust:dirs",
        "//third-party/rust:futures",
        "//third-party/rust:serde",
        "//third-party/rust:sysinfo",
        "//third-party/rust:tokio",
        "//third-party/rust:uuid",
    ] + select({
        "DEFAULT": [],
        "prelude//os:linux": [
            "//third-party/rust:nix",
        ],
        "prelude//os:macos": [
            "//third-party/rust:nix",
        ],
        "prelude//os:windows": [
            "//third-party/rust:windows-sys",
        ],
    }),
)
