load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_transition",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_build_api:buck2_build_api",
        "//app/buck2_build_api_derive:buck2_build_api_derive",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_interpreter:buck2_interpreter",
        "//app/buck2_node:buck2_node",
        "//dice/dice:dice",
        "//dice/dice_futures:dice_futures",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//pagable:pagable",
        "//starlark-rust/starlark:starlark",
        "//starlark-rust/starlark_map:starlark_map",
        "//third-party/rust:async-trait",
        "//third-party/rust:derive_more",
        "//third-party/rust:either",
        "//third-party/rust:futures",
        "//third-party/rust:itertools",
        "//third-party/rust:ref-cast",
    ],
)
