[package]
name = "yak_data"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
derive_more.workspace = true
dupe.workspace = true
gazebo.workspace = true
hex.workspace = true
pagable.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
yak_host_sharing_proto.workspace = true
yak_miniperf_proto.workspace = true
yak_proto_serde.workspace = true

[build-dependencies]
yak_protoc_dev.workspace = true

[lints]
workspace = true
