load("//build_defs:rust.bzl", "rust_library", "rust_linkable_symbol")

rust_library(
    name = "buck2_cmd_completion_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        ":completion_wrapper_bash",
        ":completion_wrapper_fish",
        ":completion_wrapper_powershell",
        ":completion_wrapper_zsh",
        ":options_wrapper_bash",
        ":options_wrapper_fish",
        ":options_wrapper_powershell",
        ":options_wrapper_zsh",
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//third-party/rust:async-trait",
        "//third-party/rust:clap",
        "//third-party/rust:clap_complete",
        "//third-party/rust:futures",
        "//third-party/rust:tokio",
    ],
)

rust_linkable_symbol(
    name = "completion_wrapper_bash",
    content_str = "src/completion/completion-wrapper.bash",
)

rust_linkable_symbol(
    name = "completion_wrapper_fish",
    content_str = "src/completion/completion-wrapper.fish",
)

rust_linkable_symbol(
    name = "completion_wrapper_zsh",
    content_str = "src/completion/completion-wrapper.zsh",
)

rust_linkable_symbol(
    name = "completion_wrapper_powershell",
    content_str = "src/completion/completion-wrapper.ps1",
)

rust_linkable_symbol(
    name = "options_wrapper_bash",
    content_str = "src/completion/options-wrapper.bash",
)

rust_linkable_symbol(
    name = "options_wrapper_fish",
    content_str = "src/completion/options-wrapper.fish",
)

rust_linkable_symbol(
    name = "options_wrapper_zsh",
    content_str = "src/completion/options-wrapper.zsh",
)

rust_linkable_symbol(
    name = "options_wrapper_powershell",
    content_str = "src/completion/options-wrapper.ps1",
)
