[package]
name = "yak_downward_api_proto"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tracing.workspace = true
yak_error.workspace = true
yak_hash.workspace = true

[build-dependencies]
yak_protoc_dev.workspace = true

[lints]
workspace = true
