load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_test_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_test_proto.proto",
    deps = [
        "//app/buck2_data:buck2_data",
        "//app/buck2_host_sharing_proto:buck2_host_sharing_proto",
        "//third-party/rust:prost-types",
    ],
)

proto_srcs(
    name = "buck2_test_proto.proto",
    srcs = ["test.proto"],
    visibility = ["PUBLIC"],
    deps = [
        "//app/buck2_data:data_proto",
    ],
)
