load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

buck_java_library(
    name = "testresultsoutput",
    srcs = [
        "TestResultsOutputEvent.java",
        "TestResultsOutputSender.java",
    ],
    source = "11",
    target = "11",
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/testresultsoutput:testresultsoutput",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/testrunner:instrumentation",
        "prelude//toolchains/android/src/com/facebook/buck/testrunner:junit",
        "prelude//toolchains/android/src/com/facebook/buck/testrunner:timeout",
        "prelude//toolchains/android/test/com/facebook/buck/testresultsoutput:testresultsoutput",
        "prelude//toolchains/android/test/com/facebook/buck/testrunner:testrunner",
        "prelude//toolchains/android/test/com/facebook/buck/testrunner:tpx_timeout_buffer_manager_test",
    ],
    deps = [
        "prelude//toolchains/android/third-party:jackson-core",
    ],
)
