[toolchain]
# When you update `channel` below, also update the two copies in
# `website/docs/getting_started/install.md`.

channel = "nightly-2026-07-05"
components = ["llvm-tools-preview", "rust-src"]
