load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "starlark_map",
    srcs = glob(["src/**/*.rs"]),
    # Controls whether to depend on the pagable crate.
    # This is independent from the "pagable" constraint on the starlark crate,
    # which controls pagable serialization/deserialization support for starlark values.
    features = ["pagable_dep"],
    rustc_flags = [
        "--cfg=rust_nightly",
    ],
    deps = [
        "//allocative/allocative:allocative",
        "//gazebo/dupe:dupe",
        "//gazebo/strong_hash:strong_hash",
        "//pagable:pagable",
        "//third-party/rust:equivalent",
        "//third-party/rust:hashbrown",
        "//third-party/rust:serde",
    ],
)
