load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_re_configuration",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_common:buck2_common",
        "//app/buck2_error:buck2_error",
    ],
)
