load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_forkserver_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_forkserver_proto.proto",
    deps = [
        "//app/buck2_data:buck2_data",
        "//gazebo/gazebo:gazebo",
        "//third-party/rust:derive_more",
        "//third-party/rust:prost-types",
    ],
)

proto_srcs(
    name = "buck2_forkserver_proto.proto",
    srcs = ["forkserver.proto"],
    visibility = ["PUBLIC"],
    deps = [
        "//app/buck2_data:data_proto",
    ],
)
