[package]
name = "yak_bxl"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
clap.workspace = true
cmp_any.workspace = true
derivative.workspace = true
derive_more.workspace = true
dice.workspace = true
dice_futures.workspace = true
display_container.workspace = true
dupe.workspace = true
either.workspace = true
futures.workspace = true
gazebo.workspace = true
itertools.workspace = true
num-bigint.workspace = true
pagable.workspace = true
serde.workspace = true
serde_json.workspace = true
starlark.workspace = true
starlark_map.workspace = true
strong_hash.workspace = true
tokio.workspace = true
yak_action_impl.workspace = true
yak_analysis.workspace = true
yak_artifact.workspace = true
yak_build_api.workspace = true
yak_cli_proto.workspace = true
yak_common.workspace = true
yak_core.workspace = true
yak_data.workspace = true
yak_error.workspace = true
yak_events.workspace = true
yak_execute.workspace = true
yak_fs.workspace = true
yak_hash.workspace = true
yak_interpreter.workspace = true
yak_interpreter_for_build.workspace = true
yak_node.workspace = true
yak_profile.workspace = true
yak_query.workspace = true
yak_query_parser.workspace = true
yak_server_ctx.workspace = true
yak_util.workspace = true

[dev-dependencies]
ctor.workspace = true
maplit.workspace = true
yak_anon_target.workspace = true
yak_transition.workspace = true

[lints]
workspace = true
