# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

buildscript.run = false

['cfg(target_os = "windows")']
buildscript.run = true
extra_deps = [
    "//third-party/win:advapi32.lib",
    "//third-party/win:avrt.lib",
    "//third-party/win:bcrypt.lib",
    "//third-party/win:bluetoothapis.lib",
    "//third-party/win:bthprops.lib",
    "//third-party/win:cfgmgr32.lib",
    "//third-party/win:comctl32.lib",
    "//third-party/win:comdlg32.lib",
    "//third-party/win:credui.lib",
    "//third-party/win:crypt32.lib",
    "//third-party/win:cryptnet.lib",
    "//third-party/win:d2d1.lib",
    "//third-party/win:d3d11.lib",
    "//third-party/win:d3d12.lib",
    "//third-party/win:d3d9.lib",
    "//third-party/win:d3dcompiler.lib",
    "//third-party/win:dbghelp.lib",
    "//third-party/win:dcomp.lib",
    "//third-party/win:dsound.lib",
    "//third-party/win:dwmapi.lib",
    "//third-party/win:dwrite.lib",
    "//third-party/win:dxgi.lib",
    "//third-party/win:dxva2.lib",
    "//third-party/win:fwpuclnt.lib",
    "//third-party/win:gdi32.lib",
    "//third-party/win:hid.lib",
    "//third-party/win:httpapi.lib",
    "//third-party/win:imm32.lib",
    "//third-party/win:iphlpapi.lib",
    "//third-party/win:kernel32.lib",
    "//third-party/win:ktmw32.lib",
    "//third-party/win:mmdevapi.lib",
    "//third-party/win:mpr.lib",
    "//third-party/win:msimg32.lib",
    "//third-party/win:mswsock.lib",
    "//third-party/win:ncrypt.lib",
    "//third-party/win:netapi32.lib",
    "//third-party/win:ntdll.lib",
    "//third-party/win:odbc32.lib",
    "//third-party/win:ole32.lib",
    "//third-party/win:oleaut32.lib",
    "//third-party/win:opengl32.lib",
    "//third-party/win:pdh.lib",
    "//third-party/win:powrprof.lib",
    "//third-party/win:psapi.lib",
    "//third-party/win:rstrtmgr.lib",
    "//third-party/win:runtimeobject.lib",
    "//third-party/win:secur32.lib",
    "//third-party/win:setupapi.lib",
    "//third-party/win:shcore.lib",
    "//third-party/win:shell32.lib",
    "//third-party/win:shlwapi.lib",
    "//third-party/win:sporder.lib",
    "//third-party/win:synchronization.lib",
    "//third-party/win:user32.lib",
    "//third-party/win:userenv.lib",
    "//third-party/win:usp10.lib",
    "//third-party/win:uxtheme.lib",
    "//third-party/win:version.lib",
    "//third-party/win:vssapi.lib",
    "//third-party/win:wer.lib",
    "//third-party/win:wevtapi.lib",
    "//third-party/win:windowscodecs.lib",
    "//third-party/win:winhttp.lib",
    "//third-party/win:wininet.lib",
    "//third-party/win:winmm.lib",
    "//third-party/win:winscard.lib",
    "//third-party/win:winspool.lib",
    "//third-party/win:wintrust.lib",
    "//third-party/win:winusb.lib",
    "//third-party/win:wlanapi.lib",
    "//third-party/win:ws2_32.lib",
    "//third-party/win:wtsapi32.lib",
    "//third-party/win:xinput.lib",
]
