load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_data",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":data_proto",
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_host_sharing_proto:buck2_host_sharing_proto",
        "//app/buck2_miniperf_proto:buck2_miniperf_proto",
        "//app/buck2_proto_serde:buck2_proto_serde",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//pagable:pagable",
        "//third-party/rust:derive_more",
        "//third-party/rust:hex",
        "//third-party/rust:prost-types",
        "//third-party/rust:serde",
    ],
)

proto_srcs(
    name = "data_proto",
    srcs = [
        "data.proto",
        "error.proto",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//app/buck2_host_sharing_proto:host_sharing.proto",
    ],
)

export_file(
    name = "error.proto",
    visibility = ["PUBLIC"],
)

export_file(
    name = "data.proto",
    visibility = ["PUBLIC"],
)
