load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "pagable_storage",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/lib.rs",
    features = ["tokio"],
    deps = [
        "//pagable:pagable",
        "//third-party/rust:anyhow",
        "//third-party/rust:async-trait",
        "//third-party/rust:bytemuck",
        "//third-party/rust:bytesize",
        "//third-party/rust:rusqlite",
        "//third-party/rust:sled",
        "//third-party/rust:tokio",
        "//third-party/rust:tracing",
    ],
)
