load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "dice_error",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//gazebo/cmp_any:cmp_any",
        "//gazebo/dupe:dupe",
        "//third-party/rust:thiserror",
    ],
)
