[package]
name = "yak_test_runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
clap.workspace = true
futures.workspace = true
host_sharing.workspace = true
parking_lot.workspace = true
tokio.workspace = true
yak_error.workspace = true
yak_grpc.workspace = true
yak_test_api.workspace = true

[lints]
workspace = true
