load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

python_library(
    name = "preprocess",
    srcs = ["preprocess.py"],
)

python_test(
    name = "preprocess_test",
    srcs = ["preprocess_test.py"],
    deps = [":preprocess"],
)

python_library(
    name = "process",
    srcs = ["process.py"],
    visibility = ["PUBLIC"],
    deps = ["prelude//apple/tools:plistlib_utils"],
)

python_test(
    name = "process_test",
    srcs = ["process_test.py"],
    deps = [":process"],
)

python_binary(
    name = "tool",
    main = "main.py",
    visibility = ["PUBLIC"],
    deps = [
        ":preprocess",
        ":process",
    ],
)
