/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Generate source file containing yak/prelude tree with contents.

use std::io;
use std::path::Path;

fn main() {
    imp().unwrap();
}

fn imp() -> io::Result<()> {
    let out_path = std::env::var_os("OUT_DIR").unwrap();
    let include_file = Path::new(&out_path).join("include.rs");
    let manifest_path = std::env::var_os("CARGO_MANIFEST_DIR").unwrap();
    let prelude_path = Path::new(&manifest_path)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("prelude");

    // Self-check.
    assert!(prelude_path.join("prelude.bzl").exists());

    println!("cargo:rerun-if-changed={}", prelude_path.display());

    write_include_file(&prelude_path, std::fs::File::create(&include_file)?)?;

    Ok(())
}

fn as_unix_like(path: &Path) -> String {
    path.to_str().unwrap().replace('\\', "/")
}

fn write_include_file(prelude: &Path, mut include_file: impl io::Write) -> io::Result<()> {
    #[allow(clippy::write_literal)]
    writeln!(include_file, "// {}generated by crate build.rs", "@")?;

    writeln!(
        include_file,
        "pub(crate) const DATA: &[crate::BundledFile] = &["
    )?;

    // A yak build runs the script in a tree of symlinks to the prelude's files. Sorting keeps the
    // output the same on every machine.
    for res in walkdir::WalkDir::new(prelude)
        .follow_links(true)
        .sort_by_file_name()
    {
        let entry = res.map_err(|e| e.into_io_error().unwrap())?;
        if !entry.file_type().is_file() {
            continue;
        }

        let path = as_unix_like(entry.path().strip_prefix(prelude).unwrap());
        writeln!(include_file, "crate::BundledFile {{")?;
        writeln!(include_file, "  path: r\"{path}\",")?;
        // The path is relative to the package, because a yak build compiles the crate in another
        // directory than the one the script ran in.
        writeln!(
            include_file,
            "  contents: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), r\"/../../prelude/{path}\")),"
        )?;

        let exec_bit;
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            exec_bit = entry.metadata()?.mode() & 0o111 != 0;
        }
        #[cfg(not(unix))]
        {
            exec_bit = false;
        }

        writeln!(include_file, "  is_executable: {exec_bit},")?;
        writeln!(include_file, "}},")?;
    }

    writeln!(include_file, "];")?;
    Ok(())
}
