load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_resource_control",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_util:buck2_util",
        "//app/buck2_wrapper_common:buck2_wrapper_common",
        "//gazebo/dupe:dupe",
        "//third-party/rust:derive_more",
        "//third-party/rust:futures",
        "//third-party/rust:ref-cast",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-util",
    ] + select({
        "DEFAULT": [],
        "prelude//os:linux": [
            "//third-party/rust:nix",
        ],
        "prelude//os:macos": [
            "//third-party/rust:nix",
        ],
    }),
)
