load("@prelude//utils:source_listing.bzl", "source_listing")

prelude = native

source_listing()

prelude.export_file(
    name = "sitecustomize.py",
    src = "sitecustomize.py",
    visibility = ["PUBLIC"],
)
