load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_cmd_docs_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_error:buck2_error",
        "//app/buck2_query:buck2_query",
        "//gazebo/dupe:dupe",
        "//third-party/rust:async-trait",
        "//third-party/rust:clap",
        "//third-party/rust:regex",
        "//third-party/rust:termimad",
    ],
)
