[package]
name = "yak_certs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rustls.workspace = true
rustls-native-certs.workspace = true
rustls-pki-types.workspace = true
tokio.workspace = true
tracing.workspace = true
yak_error.workspace = true

[lints]
workspace = true
