load("//build_defs:rust.bzl", "rust_binary", "rust_library")

rust_library(
    name = "setsketch",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party/rust:base64",
        "//third-party/rust:rand",
        "//third-party/rust:rand_distr",
        "//third-party/rust:rand_xoshiro",
    ],
)

rust_binary(
    name = "sketch_size",
    srcs = ["bin/sketch_size.rs"],
    crate_root = "bin/sketch_size.rs",
    deps = [
        ":setsketch",
        "//third-party/rust:anyhow",
    ],
)
