load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_action_metadata_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_action_metadata_proto.proto",
)

proto_srcs(
    name = "buck2_action_metadata_proto.proto",
    srcs = ["action_metadata.proto"],
    visibility = ["PUBLIC"],
)
