[package]
name = "starlark_js_example"
version = "0.0.0"
edition.workspace = true
description = "Example of running starlark-rust interpreter in browser"
repository.workspace = true
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
starlark.workspace = true

[lints]
workspace = true
