load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_directory",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_util:buck2_util",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//gazebo/strong_hash:strong_hash",
        "//pagable:pagable",
        "//shed/mini_vec:mini_vec",
        "//starlark-rust/starlark_map:starlark_map",
        "//third-party/rust:dashmap",
        "//third-party/rust:derivative",
        "//third-party/rust:derive_more",
        "//third-party/rust:either",
        "//third-party/rust:sorted_vector_map",
    ],
)
