load("@prelude//:none.bzl", "none_rule")
load("@prelude//transitions:constraint_override_registry.bzl", "constraint_override_refs", "constraint_override_registry")
load("@prelude//utils:source_listing.bzl", "source_listing")
load(":native.bzl", prelude = "native")

source_listing(
    exclude = [
        # Exclude PACKAGE file using modifiers since those are not enabled everywhere yet.
        "PACKAGE",
    ]
)

srcs = glob(
    ["**"],
    exclude = [
        "**/.pyre_configuration.local",
        # Unfortunately, using modifiers require loading bzl files in outside of prelude,
        # and that currently breaks isolated tests that attempt to grab a best-effort prelude
        # from the filegroup below.
        # TODO: Switch these tests to use the bundled prelude instead.
        "PACKAGE",
    ],
)

# Re-export filegroups that are behind package boundary violations for
# Buck2.
prelude.filegroup(
    name = "files",
    srcs = srcs,
    visibility = ["PUBLIC"],
)

# Tests want BUCK.v2 instead of TARGETS.v2
prelude.genrule(
    name = "copy_android_constraint",
    out = "BUCK",
    cmd = "cp $(location prelude//android/constraints:files)/BUCK $OUT",
    visibility = ["PUBLIC"],
)

prelude.filegroup(
    name = "prelude",
    srcs = {
        "": ":files",
        "android/constraints/BUCK": ":copy_android_constraint",
        # explicitly include files that fall off the glob due to package boundary violations
        "cfg/exec_platform/marker/BUCK": "//cfg/exec_platform/marker:buck_file",
        "rust/tools/attrs.bzl": "//rust/tools:attrs.bzl",
    },
    visibility = ["PUBLIC"],
)

none_rule(
    name = "none",
    visibility = ["PUBLIC"],
)

constraint_override_registry(
    name = "constraint_override_registry",
    refs = constraint_override_refs(),
    visibility = ["PUBLIC"],
)
