name: build_example_conan
runs:
  using: composite
  steps:
  - name: Build examples/toolchains/conan_toolchain
    run: |-
      cd examples/toolchains/conan_toolchain
      $RUNNER_TEMP/artifacts/yak init
      cp -r ../../../prelude prelude
      # Generate Conan imports. TODO[AH] Make that unnecessary.
      PATH="$RUNNER_TEMP/artifacts:$PATH" $RUNNER_TEMP/artifacts/yak run //cpp/conan:update -v 2
      $RUNNER_TEMP/artifacts/yak build //... -v 2
      $RUNNER_TEMP/artifacts/yak test //... -v 2
    shell: bash
