load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "dice_core",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/lib.rs",
    deps = [
        "//allocative/allocative:allocative",
        "//gazebo/dupe:dupe",
        "//shed/lock_free_hashtable:lock_free_hashtable",
        "//shed/mini_vec:mini_vec",
        "//third-party/rust:arc-swap",
        "//third-party/rust:smallvec",
        "//third-party/rust:triomphe",
    ],
)
