[package]
name = "allocative_derive"
version = "0.3.6"
edition.workspace = true
description = "Implementation of derive(Allocative) for allocative crate"
repository.workspace = true
license.workspace = true

[lib]
test = false
doctest = false
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
