load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_cmd_starlark_server",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_cmd_starlark_client:buck2_cmd_starlark_client",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_interpreter:buck2_interpreter",
        "//app/buck2_interpreter_for_build:buck2_interpreter_for_build",
        "//app/buck2_server_ctx:buck2_server_ctx",
        "//dice/dice:dice",
        "//gazebo/dupe:dupe",
        "//starlark-rust/starlark:starlark",
        "//third-party/rust:async-recursion",
        "//third-party/rust:async-trait",
        "//third-party/rust:serde_json",
    ],
)
