/*
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

use std::collections::BTreeMap;

use crate::GoCell;
use crate::ModuleInputs;
use crate::PLATFORMS;
use crate::generate;
use crate::list::parse_list;

const MAIN: &str = r#""Module": {"Path": "example.com/m", "Main": true, "Dir": "/src/m"}"#;
const TERM: &str = r#""Module": {"Path": "golang.org/x/term", "Version": "v0.46.0", "Dir": "/cache/golang.org/x/term@v0.46.0"}"#;
const SYS: &str = r#""Module": {"Path": "golang.org/x/sys", "Version": "v0.48.0", "Dir": "/cache/golang.org/x/sys@v0.48.0"}"#;

/// The `go list` output of a module whose `cmd/tool` binary imports `golang.org/x/term`, which
/// imports `golang.org/x/sys/unix` on macOS and Linux and `golang.org/x/sys/windows` on
/// Windows, and whose `greet` library embeds a file and has internal and external tests.
fn listing(goos: &str) -> String {
    let sys = if goos == "windows" { "windows" } else { "unix" };
    format!(
        r#"
{{"ImportPath": "fmt", "Standard": true}}
{{"ImportPath": "golang.org/x/sys/{sys}", "Name": "{sys}", "GoFiles": ["a.go"], {SYS}}}
{{"ImportPath": "golang.org/x/term", "Name": "term", "GoFiles": ["term.go"], "Imports": ["golang.org/x/sys/{sys}", "fmt"], {TERM}}}
{{"ImportPath": "example.com/m/greet", "Name": "greet", "GoFiles": ["greet.go"], "EmbedFiles": ["greeting.txt"], "TestGoFiles": ["greet_test.go"], "XTestGoFiles": ["greet_ext_test.go"], "XTestImports": ["example.com/m/greet", "golang.org/x/term"], {MAIN}}}
{{"ImportPath": "example.com/m/cmd/tool", "Name": "main", "GoFiles": ["main.go"], "Imports": ["example.com/m/greet", "golang.org/x/term", "fmt"], {MAIN}}}
{{"ImportPath": "example.com/m/greet [example.com/m/greet.test]", "Name": "greet", "ForTest": "example.com/m/greet"}}
"#
    )
}

fn generate_module(build_files: &BTreeMap<String, bool>) -> GoCell {
    let listings: Vec<_> = PLATFORMS
        .iter()
        .map(|p| parse_list(&listing(p.goos)).unwrap())
        .collect();
    generate(&ModuleInputs {
        module_dir: "m",
        cell: "gomod",
        listings: &listings,
        build_files,
    })
    .unwrap()
}

#[test]
fn third_party_packages_are_targets_of_their_module_version() {
    let cell = generate_module(&BTreeMap::new());
    let dirs: Vec<_> = cell.modules.iter().map(|m| m.dir.as_str()).collect();
    assert_eq!(
        dirs,
        ["golang.org/x/sys@v0.48.0", "golang.org/x/term@v0.46.0"]
    );
    assert_eq!(
        cell.modules[1].source_dir,
        "/cache/golang.org/x/term@v0.46.0"
    );
    assert_eq!(
        cell.modules[1].build_file,
        r#"# @generated by the go cell from `go list`.

go_library(
    name = "golang.org/x/term",
    package_name = "golang.org/x/term",
    package_root = "",
    srcs = glob(["*.go", "*.s", "*.S", "*.c", "*.h", "*.cc", "*.cpp", "*.cxx", "*.hh", "*.hpp", "*.m", "*.syso"], exclude = ["*_test.go"]),
    deps = select({"prelude//os:linux": ["//golang.org/x/sys@v0.48.0:golang.org/x/sys/unix"], "prelude//os:macos": ["//golang.org/x/sys@v0.48.0:golang.org/x/sys/unix"], "prelude//os:windows": ["//golang.org/x/sys@v0.48.0:golang.org/x/sys/windows"], "DEFAULT": []}),
    visibility = ["PUBLIC"],
)

"#
    );
    assert!(
        cell.modules[0]
            .build_file
            .contains(r#"package_root = "windows","#),
        "{}",
        cell.modules[0].build_file
    );
    assert!(cell.root_build_file.contains(
        r#"alias(
    name = "golang.org/x/sys/unix",
    actual = "//golang.org/x/sys@v0.48.0:golang.org/x/sys/unix",
"#
    ));
}

#[test]
fn first_party_packages_are_data_of_the_module_file() {
    let cell = generate_module(&BTreeMap::new());
    let module = &cell.module_file;
    assert!(module.contains("_MODULE_DIR = \"m\"\n"), "{module}");
    assert!(module.contains("_MISSING_GO_PACKAGE = []\n"), "{module}");
    assert!(
        module.contains(r#""cmd/tool": {"import_path": "example.com/m/cmd/tool", "kind": "binary", "name": "tool", "owner": "", "dir": "cmd/tool", "embeds": [], "deps": ["//m:greet", "gomod//golang.org/x/term@v0.46.0:golang.org/x/term"], "test": None}"#),
        "{module}"
    );
    assert!(
        module.contains(r#""greet": {"import_path": "example.com/m/greet", "kind": "library", "name": "greet", "owner": "", "dir": "greet", "embeds": ["greeting.txt"], "deps": [], "test": {"embeds": ["greeting.txt"], "deps": ["gomod//golang.org/x/term@v0.46.0:golang.org/x/term"]}}"#),
        "{module}"
    );
    assert!(module.contains("def go_module():"));
}

#[test]
fn the_nearest_build_file_declares_a_package() {
    let own = BTreeMap::from([("greet".to_owned(), true)]);
    let module = generate_module(&own).module_file;
    assert!(
        module.contains(r#""deps": ["//m/greet:greet", "gomod//"#),
        "{module}"
    );
    assert!(
        module.contains(r#""name": "greet", "owner": "greet", "dir": """#),
        "{module}"
    );

    let cmd = BTreeMap::from([("cmd".to_owned(), true)]);
    let module = generate_module(&cmd).module_file;
    assert!(
        module.contains(r#""cmd/tool": {"import_path": "example.com/m/cmd/tool", "kind": "binary", "name": "tool", "owner": "cmd", "dir": "tool""#),
        "{module}"
    );

    let missing = BTreeMap::from([("greet".to_owned(), false)]);
    let module = generate_module(&missing).module_file;
    assert!(
        module.contains("_MISSING_GO_PACKAGE = [\"m/greet\"]\n"),
        "{module}"
    );
}

#[test]
fn binaries_of_the_same_name_take_their_directories() {
    let output = format!(
        r#"
{{"ImportPath": "example.com/m/cmd/a/server", "Name": "main", "GoFiles": ["main.go"], {MAIN}}}
{{"ImportPath": "example.com/m/cmd/b/server", "Name": "main", "GoFiles": ["main.go"], {MAIN}}}
{{"ImportPath": "example.com/m/v2", "Name": "m", "GoFiles": ["m.go"], "Module": {{"Path": "example.com/m/v2", "Main": true}}}}
"#
    );
    let listings = vec![parse_list(&output).unwrap()];
    let cell = generate(&ModuleInputs {
        module_dir: "",
        cell: "gomod",
        listings: &listings,
        build_files: &BTreeMap::new(),
    })
    .unwrap();
    assert!(
        cell.module_file.contains(r#""name": "cmd/a/server""#),
        "{}",
        cell.module_file
    );
    assert!(cell.module_file.contains(r#""name": "cmd/b/server""#));
}

#[test]
fn a_local_replacement_fails() {
    let output = format!(
        r#"
{{"ImportPath": "example.com/m", "Name": "m", "GoFiles": ["m.go"], "Imports": ["example.com/lib"], {MAIN}}}
{{"ImportPath": "example.com/lib", "Name": "lib", "GoFiles": ["lib.go"], "Module": {{"Path": "example.com/lib", "Version": "v1.0.0", "Replace": {{"Path": "../lib", "Dir": "/src/lib"}}}}}}
"#
    );
    let listings = vec![parse_list(&output).unwrap()];
    let error = generate(&ModuleInputs {
        module_dir: "",
        cell: "gomod",
        listings: &listings,
        build_files: &BTreeMap::new(),
    })
    .err()
    .unwrap()
    .to_string();
    assert!(
        error.contains("`example.com/lib` is replaced by a local directory"),
        "{error}"
    );
}
