[package]
name = "yak_test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
async-trait.workspace = true
derive_more.workspace = true
dice.workspace = true
dice_futures.workspace = true
display_container.workspace = true
dupe.workspace = true
futures.workspace = true
host_sharing.workspace = true
itertools.workspace = true
pagable.workspace = true
remote_execution.workspace = true
serde.workspace = true
serde_json.workspace = true
sorted_vector_map.workspace = true
tokio.workspace = true
tracing.workspace = true
yak_build_api.workspace = true
yak_build_signals.workspace = true
yak_cli_proto.workspace = true
yak_common.workspace = true
yak_core.workspace = true
yak_data.workspace = true
yak_downward_api.workspace = true
yak_error.workspace = true
yak_error_derive.workspace = true
yak_events.workspace = true
yak_execute.workspace = true
yak_execute_impl.workspace = true
yak_external_cells_cargo.workspace = true
yak_fs.workspace = true
yak_grpc.workspace = true
yak_hash.workspace = true
yak_interpreter.workspace = true
yak_interpreter_for_build.workspace = true
yak_node.workspace = true
yak_resource_control.workspace = true
yak_server_ctx.workspace = true
yak_test_api.workspace = true
yak_util.workspace = true

[dev-dependencies]
maplit.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true

[lints]
workspace = true
