load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_profile",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_interpreter:buck2_interpreter",
        "//starlark-rust/starlark:starlark",
        "//third-party/rust:inferno",
    ],
)
