load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_offline_archive",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_util:buck2_util",
        "//third-party/rust:serde",
    ],
)
