load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_query_parser",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_error:buck2_error",
        "//app/buck2_util:buck2_util",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//third-party/rust:derive_more",
        "//third-party/rust:enum-map",
        "//third-party/rust:nom",
        "//third-party/rust:nom-language",
    ],
)
