[package]
name = "yak_host_sharing_proto"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
prost.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
yak_protoc_dev.workspace = true

[lints]
workspace = true
