load("//build_defs:rust.bzl", "rust_binary")

rust_binary(
    name = "use_some_memory",
    srcs = ["use_some_memory.rs"],
    crate_root = "use_some_memory.rs",
    deps = [
        "//third-party/rust:clap",
    ],
)
