[package]
name = "yak_test_api"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocative.workspace = true
async-trait.workspace = true
derivative.workspace = true
derive_more.workspace = true
dupe.workspace = true
futures.workspace = true
gazebo.workspace = true
host_sharing.workspace = true
pagable.workspace = true
prost-types.workspace = true
sorted_vector_map.workspace = true
tokio.workspace = true
tonic.workspace = true
tower-layer.workspace = true
tower-service.workspace = true
tracing.workspace = true
yak_core.workspace = true
yak_data.workspace = true
yak_downward_api.workspace = true
yak_downward_api_proto.workspace = true
yak_error.workspace = true
yak_events.workspace = true
yak_fs.workspace = true
yak_grpc.workspace = true
yak_hash.workspace = true
yak_host_sharing_proto.workspace = true
yak_test_proto.workspace = true

[dev-dependencies]
assert_matches.workspace = true

[lints]
workspace = true
