load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "host_sharing",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//allocative/allocative:allocative",
        "//pagable:pagable",
        "//starlark-rust/starlark_map:starlark_map",
        "//third-party/rust:anyhow",
        "//third-party/rust:dashmap",
        "//third-party/rust:futures-intrusive",
    ],
)
