load("//build_defs:rust.bzl", "rust_library", "rust_test")

rust_library(
    name = "buck2_core",
    srcs = glob(
        ["src/**/*.rs"],
    )
    + ["src/pattern/target_pattern.md"],
    doc_deps = [
        "//third-party/rust:maplit",
    ],
    doctests = select({
        "DEFAULT": True,
        # ```
        # The command line is too long.
        # Couldn't compile the test.
        # ```
        "prelude//os:windows": False,
    }),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_data:buck2_data",
        "//app/buck2_env:buck2_env",
        "//app/buck2_error:buck2_error",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_util:buck2_util",
        "//gazebo/cmp_any:cmp_any",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//gazebo/strong_hash:strong_hash",
        "//pagable:pagable",
        "//shed/lock_free_hashtable:lock_free_hashtable",
        "//shed/static_interner:static_interner",
        "//starlark-rust/starlark_map:starlark_map",
        "//third-party/rust:blake3",
        "//third-party/rust:compact_str",
        "//third-party/rust:ctor",
        "//third-party/rust:derivative",
        "//third-party/rust:derive_more",
        "//third-party/rust:equivalent",
        "//third-party/rust:futures",
        "//third-party/rust:hex",
        "//third-party/rust:hostname",
        "//third-party/rust:itertools",
        "//third-party/rust:memchr",
        "//third-party/rust:os_str_bytes",
        "//third-party/rust:pin-project",
        "//third-party/rust:rand",
        "//third-party/rust:ref-cast",
        "//third-party/rust:regex",
        "//third-party/rust:sequence_trie",
        "//third-party/rust:serde",
        "//third-party/rust:smallvec",
        "//third-party/rust:tempfile",
        "//third-party/rust:tokio",
        "//third-party/rust:tracing",
        "//third-party/rust:tracing-subscriber",
        "//third-party/rust:triomphe",
    ] + select({
        "DEFAULT": [],
        "prelude//os:windows": [
            "//third-party/rust:common-path",
        ],
    }),
)

rust_test(
    name = "soft_error",
    srcs = [
        "tests/soft_error.rs",
    ],
    deps = [
        ":buck2_core",
        "//app/buck2_error:buck2_error",
    ],
)
