load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_daemon",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_common:buck2_common",
        "//app/buck2_core:buck2_core",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_resource_control:buck2_resource_control",
        "//app/buck2_server:buck2_server",
        "//app/buck2_util:buck2_util",
        "//dice/dice:dice",
        "//gazebo/dupe:dupe",
        "//third-party/rust:clap",
        "//third-party/rust:futures",
        "//third-party/rust:libc",
        "//third-party/rust:rand",
        "//third-party/rust:serde_json",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-stream",
        "//third-party/rust:tracing",
    ]
    + select({
        "DEFAULT": [],
        "prelude//os:linux": [
            "//third-party/rust:nix",
        ],
        "prelude//os:macos": [
            "//third-party/rust:nix",
        ],
    }),
)
