load("//build_defs:proto.bzl", "proto_srcs", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2_downward_api_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_downward_api_proto.proto",
    deps = [
        "//app/buck2_error:buck2_error",
        "//app/buck2_hash:buck2_hash",
        "//third-party/rust:tracing",
    ],
)

proto_srcs(
    name = "buck2_downward_api_proto.proto",
    srcs = ["downward_api.proto"],
    visibility = ["PUBLIC"],
)
