[package]
name = "starlark_derive"
version = "0.14.2"
edition.workspace = true
description = "Derive helpers for the starlark package."
repository.workspace = true
license = "Apache-2.0"

[lib]
test = false
doctest = false
proc-macro = true

[dependencies]
dupe.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
