[package]
name = "yak_action_metadata_proto"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
yak_protoc_dev.workspace = true

[lints]
workspace = true
