load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_binary", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

buck_java_library(
    name = "abi",
    srcs = glob(
        ["*.java"],
        exclude = [
            "ApiStubber.java",
        ],
    ),
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/jvm/java/abi:abi",
    ],
    versioned_java_srcs = True,
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:steps",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:support",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/stepsbuilder/javacd/main:command_lib",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/workertool:command_lib",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/workertool/postexecutors:postexecutors",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/java/abi/...",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/cd/workertool/postexecutors:postexecutors",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:javacd-model",
        "prelude//toolchains/android/src/com/facebook/buck/io/filesystem/impl:utils",
        "prelude//toolchains/android/src/com/facebook/buck/io/pathformat:pathformat",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/kotlin:kotlin",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/source/api:api",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/lang/extra:extra",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/lang/model:model",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/plugin/api:api",
        "prelude//toolchains/android/src/com/facebook/buck/util:util",
        "prelude//toolchains/android/src/com/facebook/buck/util/function:function",
        "prelude//toolchains/android/third-party:asm",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:infer-annotations",
        "prelude//toolchains/android/third-party:jsr305",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util/zip:zip",
    ],
)

alias(
    name = "api-stubber",
    actual = ":api-stubber-main",
    visibility = ["PUBLIC"],
)

buck_java_binary(
    name = "api-stubber-main",
    main_class = "com.facebook.buck.jvm.java.abi.ApiStubber",
    deps = [
        ":lib-api-stubber",
    ],
)

buck_java_library(
    name = "lib-api-stubber",
    srcs = ["ApiStubber.java"],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
        ":abi",
    ],
)
