[package]
name = "yak_critical_path"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
crossbeam.workspace = true
derive_more.workspace = true
starlark_map.workspace = true
yak_error.workspace = true

[dev-dependencies]
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
yak_hash.workspace = true

[lints]
workspace = true
