load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

export_file(
    name = "xcode_version_checker",
    labels = ["buck2-only"],
    mode = "reference",
    visibility = ["PUBLIC"],
)
