load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_proto_serde",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party/rust:prost-types",
        "//third-party/rust:serde",
    ],
)
