load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "dice_futures",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//gazebo/dupe:dupe",
        "//shed/mini_vec:mini_vec",
        "//third-party/rust:futures",
        "//third-party/rust:parking_lot",
        "//third-party/rust:pin-project",
        "//third-party/rust:smallvec",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
)
