load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_cmd_starlark_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_cli_proto:buck2_cli_proto",
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_common:buck2_common",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_event_observer:buck2_event_observer",
        "//app/buck2_events:buck2_events",
        "//third-party/rust:async-trait",
        "//third-party/rust:clap",
        "//third-party/rust:debugserver-types",
        "//third-party/rust:futures",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
    ],
)
