load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_grpc",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//app/buck2_error:buck2_error",
        "//third-party/rust:futures",
        "//third-party/rust:hyper",
        "//third-party/rust:hyper-util",
        "//third-party/rust:pin-project",
        "//third-party/rust:tokio",
        "//third-party/rust:tonic",
        "//third-party/rust:tower",
    ],
)
