load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_certs",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//app/buck2_error:buck2_error",
        "//third-party/rust:rustls",
        "//third-party/rust:rustls-native-certs",
        "//third-party/rust:rustls-pki-types",
        "//third-party/rust:tokio",
        "//third-party/rust:tracing",
    ],
)
