[package]
name = "yak_event_observer"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
derivative.workspace = true
dupe.workspace = true
gazebo.workspace = true
linked-hash-map.workspace = true
prost-types.workspace = true
regex.workspace = true
shlex.workspace = true
starlark_map.workspace = true
superconsole.workspace = true
termwiz.workspace = true
tracing.workspace = true
yak_common.workspace = true
yak_data.workspace = true
yak_error.workspace = true
yak_events.workspace = true
yak_hash.workspace = true
yak_test_api.workspace = true
yak_util.workspace = true
yak_wrapper_common.workspace = true

[dev-dependencies]
assert_matches.workspace = true

[lints]
workspace = true
