/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Error types for filesystem operations.

use std::io;

use tokio::task::JoinError;
use yak_error::ErrorTag;

use crate::paths::abs_path::AbsPath;

/// The inner error type that IoError can hold.
#[derive(Debug)]
pub enum IoErrorSource {
    Io(io::Error),
    Internal(yak_error::Error),
}

impl From<io::Error> for IoErrorSource {
    fn from(e: io::Error) -> Self {
        IoErrorSource::Io(e)
    }
}

impl IoError {
    /// Create an error from an io::Error or yak_error::Error.
    pub fn new<T: Into<IoErrorSource>>(e: T) -> Self {
        Self {
            source: e.into(),
            context: Vec::new(),
            tags: Vec::new(),
            is_input_path: None,
            not_found_tag: None,
        }
    }

    pub fn internal(e: yak_error::Error) -> Self {
        Self::new(IoErrorSource::Internal(e))
    }

    pub fn from_join(e: JoinError) -> Self {
        Self::internal(yak_error::Error::from(e))
    }

    /// Set operation based on provided path.
    pub fn new_with_path<T: Into<IoErrorSource>, P: AsRef<AbsPath>>(
        op: &str,
        path: P,
        e: T,
    ) -> Self {
        IoError::new(e).context(format!("{}({})", op, path.as_ref().display()))
    }

    pub fn context(mut self, op: impl Into<String>) -> Self {
        self.context.push(op.into());
        self
    }

    pub fn tag(mut self, tag: ErrorTag) -> Self {
        self.tags.push(tag);
        self
    }

    pub fn inner_error(self) -> IoErrorSource {
        self.source
    }

    pub fn io_error_kind(&self) -> Option<io::ErrorKind> {
        match &self.source {
            IoErrorSource::Io(e) => Some(e.kind()),
            IoErrorSource::Internal(_) => None,
        }
    }

    fn convert_to_yak_error(self) -> yak_error::Error {
        let mut tags = vec![ErrorTag::IoSystem];

        if let IoErrorSource::Io(e) = &self.source {
            if e.kind() == io::ErrorKind::NotFound {
                tags.extend(self.not_found_tag);
            }
            if e.kind() == io::ErrorKind::NotADirectory {
                if self.is_input_path == Some(true) {
                    tags.push(ErrorTag::InputPathNotADirectory);
                }
            }
        }

        tags.extend(self.tags);
        let context = self.context.clone();
        let source_error: yak_error::Error = match self.source {
            IoErrorSource::Io(e) => e.into(),
            IoErrorSource::Internal(e) => e,
        };
        let mut result = source_error.tag(tags);
        for ctx in context.into_iter().rev() {
            result = result.context(ctx);
        }
        result
    }

    /// Convert to a yak_error::Error, applying `tag` if the path was missing.
    ///
    /// The tag names a path that was not there, so it is only meaningful for `NotFound`. Other
    /// error kinds from the same call - permission denied and friends - keep the categorization
    /// they already have rather than being labelled missing.
    pub fn categorize_tagged(mut self, tag: ErrorTag) -> yak_error::Error {
        self.not_found_tag = Some(tag);
        self.convert_to_yak_error()
    }

    /// Convert to a yak_error::Error and tag as an input error if a path is missing.
    /// This should be used if the path was user provided,
    /// from a source file, configuration or CLI argument.
    pub fn categorize_input(mut self) -> yak_error::Error {
        self.is_input_path = Some(true);
        self.categorize_tagged(ErrorTag::MissingInputPath)
    }

    /// Convert to a yak_error::Error and tag as a tier0 error if a path is missing.
    /// This should be used if the path was not user provided,
    /// generated by yak or internal infra.
    /// This is also used by functions in fs_util that should never produce an error
    /// with kind==ErrorKind::NotFound, such as *_if_exists functions.
    pub fn categorize_internal(mut self) -> yak_error::Error {
        self.is_input_path = Some(false);
        self.categorize_tagged(ErrorTag::MissingInternalPath)
    }

    /// Convert to a yak_error::Error with no tags, new code should only use this in tests
    pub fn uncategorized(self) -> yak_error::Error {
        self.convert_to_yak_error()
    }
}

#[derive(Debug)]
pub struct IoError {
    pub(crate) source: IoErrorSource,
    pub(crate) context: Vec<String>,
    pub(crate) tags: Vec<ErrorTag>,
    pub(crate) is_input_path: Option<bool>,
    pub(crate) not_found_tag: Option<ErrorTag>,
}

pub trait IoResultExt<T> {
    fn categorize_input(self) -> yak_error::Result<T>;
    fn categorize_internal(self) -> yak_error::Result<T>;
    /// See [`IoError::categorize_tagged`].
    fn categorize_tagged(self, tag: ErrorTag) -> yak_error::Result<T>;
    fn uncategorized(self) -> yak_error::Result<T>;
}

impl<T> IoResultExt<T> for Result<T, IoError> {
    fn categorize_tagged(self, tag: ErrorTag) -> yak_error::Result<T> {
        self.map_err(|e| e.categorize_tagged(tag))
    }
    fn categorize_input(self) -> yak_error::Result<T> {
        self.map_err(|e| e.categorize_input())
    }
    fn categorize_internal(self) -> yak_error::Result<T> {
        self.map_err(|e| e.categorize_internal())
    }
    fn uncategorized(self) -> yak_error::Result<T> {
        self.map_err(|e| e.uncategorized())
    }
}
