load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

buck_java_library(
    name = "quoter",
    srcs = ["Quoter.java"],
    source = "11",
    target = "11",
    visibility = ["PUBLIC"],
    deps = [],
)

buck_java_library(
    name = "utils",
    srcs = ["EscaperUtils.java"],
    source = "11",
    target = "11",
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/third-party:guava",
        ":quoter",
    ],
)

buck_java_library(
    name = "bash",
    srcs = ["BashEscaper.java"],
    source = "11",
    target = "11",
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/third-party:guava",
        ":quoter",
        ":utils",
    ],
)
