load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_hash",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//gazebo/dupe:dupe",
        "//third-party/rust:dashmap",
        "//third-party/rust:fxhash",
        "//third-party/rust:indexmap",
    ],
)
