/*
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Translates the third-party packages of `cargo metadata` into the build files of the cargo
//! cell. Each package is a package of the cell, whose sources are the files that Cargo downloaded.

use std::collections::HashMap;
use std::path::Path;

use yak_external_cells_starlark::Value;
use yak_external_cells_starlark::call;

use crate::graph::CargoPlatform;
use crate::graph::GenerateError;
use crate::graph::Graph;
use crate::graph::crate_name;
use crate::graph::lib_target;
use crate::graph::package_env;
use crate::graph::relative_to;
use crate::graph::target_id;
use crate::metadata::Metadata;
use crate::metadata::Node;
use crate::metadata::Package;

/// The sources of a package in the cell, which are all the files of its directory except the
/// generated build file. `**` matches no name that starts with a dot.
const SRCS: &str = "glob([\"**\", \"**/.*\", \"**/.*/**\"], exclude = [\"YAK\"])";

/// ThirdParty holds the files of the third-party packages in the cargo cell.
#[derive(Debug)]
pub struct ThirdParty {
    /// The build file at the root of the cell. It holds an alias per package, named
    /// `<name>-<version>`, and an alias named after the package when it has one version in the
    /// graph.
    pub root_build_file: String,
    /// Sorted by directory.
    pub packages: Vec<ThirdPartyPackage>,
}

/// ThirdPartyPackage is a third-party package of the cargo cell.
#[derive(Debug)]
pub struct ThirdPartyPackage {
    /// The package's directory in the cell (`cell_dir`).
    pub dir: String,
    /// The absolute path of the directory that holds the package's manifest, where Cargo put
    /// its sources.
    pub source_dir: String,
    /// The package's build file.
    pub build_file: String,
}

/// The sources of crates.io. A package that source replacement takes from elsewhere keeps its
/// crates.io source, and Cargo checks it against the checksum of the crates.io package.
const CRATES_IO: &[&str] = &[
    "registry+https://github.com/rust-lang/crates.io-index",
    "sparse+https://index.crates.io/",
];

/// The directory of a third-party package in the cell. The cell keeps a copy of a package's
/// sources under this name, so the name identifies the sources. A crates.io package is
/// `<name>-<version>`. A package from another source, such as another registry or a Git
/// repository, also gets a hash of its package ID and source. The source of a Git package names
/// the commit, and its package ID does not.
pub(crate) fn cell_dir(package: &Package) -> String {
    match &package.source {
        Some(source) if CRATES_IO.contains(&source.as_str()) => target_id(package),
        source => {
            let identity = format!("{}\n{}", package.id, source.as_deref().unwrap_or(""));
            format!("{}-{:08x}", target_id(package), fnv1a(&identity) as u32)
        }
    }
}

/// The 64-bit FNV-1a hash, which stays the same across yak versions.
fn fnv1a(s: &str) -> u64 {
    s.bytes().fold(0xcbf29ce484222325, |hash, byte| {
        (hash ^ u64::from(byte)).wrapping_mul(0x100000001b3)
    })
}

/// The label of the library of a third-party package, relative to the cell.
pub(crate) fn library_label(package: &Package) -> String {
    format!("//{}:{}", cell_dir(package), package.name)
}

fn package_dir(package: &Package) -> &Path {
    Path::new(&package.manifest_path)
        .parent()
        .unwrap_or(Path::new(""))
}

fn build_file(
    graph: &Graph<'_>,
    package: &Package,
    node: &Node,
    platforms: &[CargoPlatform],
) -> yak_error::Result<Option<String>> {
    let Some(lib) = lib_target(package) else {
        // A package without a library, such as a binary, cannot be a dependency.
        return Ok(None);
    };
    let dir = package_dir(package);
    let deps = graph.deps(node, platforms, |p| Ok(library_label(p)))?;
    let (normal, build) = (deps.normal, deps.build);
    let features = Value::strs(node.features.iter().cloned());
    let mut env = package_env(package);
    env.push(("CARGO_MANIFEST_DIR".to_owned(), Value::str(".")));
    let mut rustc_flags = Vec::new();
    let mut lib_deps = normal.deps.clone();

    let mut out = String::from("# @generated by the cargo cell of yak from `cargo metadata`.\n\n");
    let script = package.targets.iter().find(|t| t.is_build_script());
    if script.is_some() {
        out.push_str("load(\"@prelude//rust:cargo_buildscript.bzl\", \"buildscript_run\")\n");
    }
    out.push_str("load(\"@prelude//rust:cargo_package.bzl\", \"cargo\")\n\n");

    if let Some(script) = script {
        let name = &package.name;
        call(
            &mut out,
            "filegroup",
            &[
                ("name", Value::str(format!("{name}-manifest-dir"))),
                ("srcs", Value::Expr(SRCS.to_owned())),
            ],
        );
        call(
            &mut out,
            "cargo.rust_binary",
            &[
                ("name", Value::str(format!("{name}-build-script-build"))),
                ("crate", Value::str("build_script_build")),
                (
                    "crate_root",
                    Value::Str(relative_to(dir, &script.src_path)?),
                ),
                ("srcs", Value::Expr(SRCS.to_owned())),
                ("edition", Value::str(&script.edition)),
                ("features", features.clone()),
                ("deps", build.deps_value()),
                ("named_deps", build.named_deps_value()),
                ("platform", build.platform_value()),
                ("env", Value::Dict(env.clone())),
                ("visibility", Value::strs::<&str>([])),
            ],
        );
        call(
            &mut out,
            "buildscript_run",
            &[
                ("name", Value::str(format!("{name}-build-script-run"))),
                (
                    "buildscript_rule",
                    Value::str(format!(":{name}-build-script-build")),
                ),
                ("package_name", Value::str(name)),
                ("version", Value::str(&package.version)),
                ("features", features.clone()),
                ("manifest_dir", Value::str(format!(":{name}-manifest-dir"))),
                ("env", Value::Dict(env.clone())),
                // Cargo links the libraries that a build script names, such as a C library that
                // the script compiled into `OUT_DIR`.
                ("rustc_link_lib", Value::Bool(true)),
                ("rustc_link_search", Value::Bool(true)),
            ],
        );
        env.push((
            "OUT_DIR".to_owned(),
            Value::str(format!("$(location :{name}-build-script-run[out_dir])")),
        ));
        rustc_flags.push(format!(
            "@$(location :{name}-build-script-run[rustc_flags])"
        ));
        // The run target carries the search paths of the host libraries that the script links
        // to every link of a dependent.
        lib_deps.push(format!(":{name}-build-script-run"));
    }

    let mut kwargs = vec![
        ("name", Value::str(&package.name)),
        ("crate", Value::str(crate_name(&lib.name))),
        ("crate_root", Value::Str(relative_to(dir, &lib.src_path)?)),
        ("srcs", Value::Expr(SRCS.to_owned())),
        ("edition", Value::str(&lib.edition)),
        ("features", features),
        ("deps", Value::strs(lib_deps)),
        ("named_deps", normal.named_deps_value()),
        ("platform", normal.platform_value()),
        ("env", Value::Dict(env)),
        ("rustc_flags", Value::strs(rustc_flags)),
        ("visibility", Value::strs(["PUBLIC"])),
    ];
    if lib.is_proc_macro() {
        kwargs.push(("proc_macro", Value::Bool(true)));
    }
    call(&mut out, "cargo.rust_library", &kwargs);
    Ok(Some(out))
}

/// Writes the build files of the third-party packages. A package's library is a
/// `cargo.rust_library`, and a package with a build script also gets a `cargo.rust_binary` and a
/// `buildscript_run` for it. Packages come from any source that Cargo downloads from, such as a
/// registry or a Git repository. A path dependency outside the workspace is an error, because
/// the cell treats a package's sources as unchanging.
pub fn generate_third_party(
    metadata: &Metadata,
    platforms: &[CargoPlatform],
) -> yak_error::Result<ThirdParty> {
    let graph = Graph::new(metadata);

    let mut nodes: Vec<(&Package, &Node)> = Vec::new();
    for node in &metadata.resolve.nodes {
        if graph.is_member(&node.id) {
            continue;
        }
        let package = graph.package(&node.id)?;
        if package.source.is_none() {
            return Err(GenerateError::PathOutsideWorkspace(target_id(package)).into());
        }
        nodes.push((package, node));
    }
    nodes.sort_by(|a, b| (&a.0.name, &a.0.version).cmp(&(&b.0.name, &b.0.version)));

    let mut versions: HashMap<&str, usize> = HashMap::new();
    for (package, _) in &nodes {
        *versions.entry(package.name.as_str()).or_default() += 1;
    }

    let mut root_build_file =
        String::from("# @generated by the cargo cell of yak from `cargo metadata`.\n\n");
    let mut packages: Vec<ThirdPartyPackage> = Vec::new();
    for (package, node) in nodes {
        let Some(build_file) = build_file(&graph, package, node, platforms)? else {
            continue;
        };
        let dir = cell_dir(package);
        if packages.iter().any(|p| p.dir == dir) {
            return Err(GenerateError::DuplicatePackage(dir).into());
        }
        let mut names = vec![target_id(package)];
        if versions[package.name.as_str()] == 1 {
            names.push(package.name.clone());
        }
        for name in names {
            call(
                &mut root_build_file,
                "alias",
                &[
                    ("name", Value::Str(name)),
                    ("actual", Value::str(library_label(package))),
                    ("visibility", Value::strs(["PUBLIC"])),
                ],
            );
        }
        packages.push(ThirdPartyPackage {
            dir,
            source_dir: package_dir(package).to_string_lossy().into_owned(),
            build_file,
        });
    }
    Ok(ThirdParty {
        root_build_file,
        packages,
    })
}
