/*
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Translates the third-party packages of `cargo metadata` into a build file.

use std::collections::HashMap;
use std::path::Path;

use crate::graph::CargoPlatform;
use crate::graph::GenerateError;
use crate::graph::Graph;
use crate::graph::crate_name;
use crate::graph::lib_target;
use crate::graph::package_env;
use crate::graph::relative_to;
use crate::graph::target_id;
use crate::metadata::Checksums;
use crate::metadata::Metadata;
use crate::metadata::Node;
use crate::metadata::Package;
use crate::starlark::Value;
use crate::starlark::call;

const CRATES_IO: &[&str] = &[
    "registry+https://github.com/rust-lang/crates.io-index",
    "sparse+https://index.crates.io/",
];

/// The path of `path` inside the package's archive, which unpacks to the directory of its
/// manifest.
fn archive_path(package: &Package, path: &str) -> yak_error::Result<String> {
    let dir = Path::new(&package.manifest_path)
        .parent()
        .unwrap_or(Path::new(""));
    Ok(format!(
        "{}.crate/{}",
        target_id(package),
        relative_to(dir, path)?
    ))
}

/// Writes the build file of the third-party packages: for each one an `http_archive` of its
/// crate, a `cargo.rust_library`, and for a package with a build script a `cargo.rust_binary` and
/// a `buildscript_run`. A package whose name has one version in the graph also gets an alias
/// named after the package.
pub fn generate_third_party(
    metadata: &Metadata,
    checksums: &Checksums,
    platforms: &[CargoPlatform],
) -> yak_error::Result<String> {
    let graph = Graph::new(metadata);

    let mut nodes: Vec<(&Package, &Node)> = Vec::new();
    for node in &metadata.resolve.nodes {
        if graph.is_member(&node.id) {
            continue;
        }
        let package = graph.package(&node.id)?;
        match &package.source {
            None => return Err(GenerateError::PathOutsideWorkspace(target_id(package)).into()),
            Some(source) if !CRATES_IO.contains(&source.as_str()) => {
                return Err(
                    GenerateError::UnsupportedSource(target_id(package), source.clone()).into(),
                );
            }
            Some(_) => {}
        }
        nodes.push((package, node));
    }
    nodes.sort_by(|a, b| (&a.0.name, &a.0.version).cmp(&(&b.0.name, &b.0.version)));

    let mut versions: HashMap<&str, usize> = HashMap::new();
    for (package, _) in &nodes {
        *versions.entry(package.name.as_str()).or_default() += 1;
    }

    let mut out = String::from(
        "# @generated by the cargo cell of yak from `cargo metadata`.\n\n\
         load(\"@prelude//rust:cargo_buildscript.bzl\", \"buildscript_run\")\n\
         load(\"@prelude//rust:cargo_package.bzl\", \"cargo\")\n\n",
    );
    for (package, node) in nodes {
        let Some(lib) = lib_target(package) else {
            // A package without a library, such as a binary, cannot be a dependency.
            continue;
        };
        let id = target_id(package);
        let archive = format!("{id}.crate");
        let checksum = checksums
            .get(&package.name, &package.version)
            .ok_or_else(|| GenerateError::MissingChecksum(id.clone()))?;
        call(
            &mut out,
            "http_archive",
            &[
                ("name", Value::str(&archive)),
                (
                    "urls",
                    Value::strs([format!(
                        "https://static.crates.io/crates/{}/{id}.crate",
                        package.name
                    )]),
                ),
                ("sha256", Value::str(checksum)),
                ("strip_prefix", Value::str(&id)),
                ("type", Value::str("tar.gz")),
            ],
        );

        let deps = graph.deps(node, platforms, |p| Ok(format!(":{}", target_id(p))))?;
        let (normal, build) = (deps.normal, deps.build);
        let features = Value::strs(node.features.iter().cloned());
        let mut env = package_env(package);
        let mut rustc_flags = Vec::new();

        if let Some(script) = package.targets.iter().find(|t| t.is_build_script()) {
            let script_build = format!("{id}-build-script-build");
            let script_run = format!("{id}-build-script-run");
            call(
                &mut out,
                "cargo.rust_binary",
                &[
                    ("name", Value::str(&script_build)),
                    ("crate", Value::str("build_script_build")),
                    (
                        "crate_root",
                        Value::str(archive_path(package, &script.src_path)?),
                    ),
                    ("srcs", Value::strs([format!(":{archive}")])),
                    ("edition", Value::str(&script.edition)),
                    ("features", features.clone()),
                    ("deps", build.deps_value()),
                    ("named_deps", build.named_deps_value()),
                    ("platform", build.platform_value()),
                    ("env", Value::Dict(env.clone())),
                    ("visibility", Value::strs::<&str>([])),
                ],
            );
            call(
                &mut out,
                "buildscript_run",
                &[
                    ("name", Value::str(&script_run)),
                    ("buildscript_rule", Value::str(format!(":{script_build}"))),
                    ("package_name", Value::str(&package.name)),
                    ("version", Value::str(&package.version)),
                    ("features", features.clone()),
                    ("manifest_dir", Value::str(format!(":{archive}"))),
                    ("env", Value::Dict(env.clone())),
                ],
            );
            env.push((
                "OUT_DIR".to_owned(),
                Value::str(format!("$(location :{script_run}[out_dir])")),
            ));
            rustc_flags.push(format!("@$(location :{script_run}[rustc_flags])"));
        }

        env.push(("CARGO_MANIFEST_DIR".to_owned(), Value::str(&archive)));
        let mut kwargs = vec![
            ("name", Value::str(&id)),
            ("crate", Value::str(crate_name(&lib.name))),
            (
                "crate_root",
                Value::str(archive_path(package, &lib.src_path)?),
            ),
            ("srcs", Value::strs([format!(":{archive}")])),
            ("edition", Value::str(&lib.edition)),
            ("features", features),
            ("deps", normal.deps_value()),
            ("named_deps", normal.named_deps_value()),
            ("platform", normal.platform_value()),
            ("env", Value::Dict(env)),
            ("rustc_flags", Value::strs(rustc_flags)),
            ("visibility", Value::strs(["PUBLIC"])),
        ];
        if lib.is_proc_macro() {
            kwargs.push(("proc_macro", Value::Bool(true)));
        }
        call(&mut out, "cargo.rust_library", &kwargs);

        if versions[package.name.as_str()] == 1 {
            call(
                &mut out,
                "alias",
                &[
                    ("name", Value::str(&package.name)),
                    ("actual", Value::str(format!(":{id}"))),
                    ("visibility", Value::strs(["PUBLIC"])),
                ],
            );
        }
    }
    Ok(out)
}
