load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_validation",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_artifact:buck2_artifact",
        "//app/buck2_build_api:buck2_build_api",
        "//app/buck2_core:buck2_core",
        "//app/buck2_error:buck2_error",
        "//app/buck2_execute:buck2_execute",
        "//app/buck2_fs:buck2_fs",
        "//dice/dice:dice",
        "//dice/dice_error:dice_error",
        "//gazebo/dupe:dupe",
        "//pagable:pagable",
        "//third-party/rust:async-trait",
        "//third-party/rust:derivative",
        "//third-party/rust:derive_more",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
    ],
)
