load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "mini_vec",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    rustc_flags = [
        "--cfg=rust_nightly",
    ],
    deps = [
        "//allocative/allocative:allocative",
        "//gazebo/dupe:dupe",
        "//gazebo/strong_hash:strong_hash",
        "//pagable:pagable",
    ],
)
