load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_build_signals",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_events:buck2_events",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//app/buck2_util:buck2_util",
        "//dice/dice:dice",
        "//gazebo/cmp_any:cmp_any",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//third-party/rust:async-trait",
        "//third-party/rust:derive_more",
        "//third-party/rust:tokio",
    ],
)
