load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_fs",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//allocative/allocative:allocative",
        "//app/buck2_env:buck2_env",
        "//app/buck2_error:buck2_error",
        "//app/buck2_util:buck2_util",
        "//gazebo/dupe:dupe",
        "//gazebo/gazebo:gazebo",
        "//gazebo/strong_hash:strong_hash",
        "//pagable:pagable",
        "//third-party/rust:compact_str",
        "//third-party/rust:derive_more",
        "//third-party/rust:dunce",
        "//third-party/rust:memchr",
        "//third-party/rust:ref-cast",
        "//third-party/rust:serde",
        "//third-party/rust:smallvec",
        "//third-party/rust:tokio",
    ] + select({
        "DEFAULT": [],
        "prelude//os:linux": [
            "//third-party/rust:libc",
            "//third-party/rust:nix",
        ],
        "prelude//os:macos": [
            "//third-party/rust:libc",
            "//third-party/rust:nix",
        ],
        "prelude//os:windows": [
            "//third-party/rust:common-path",
            "//third-party/rust:windows-sys",
        ],
    }),
)
