[package]
name = "yak_cmd_targets_server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-recursion.workspace = true
async-trait.workspace = true
blake3.workspace = true
derive_more.workspace = true
dice.workspace = true
dice_futures.workspace = true
dupe.workspace = true
flate2.workspace = true
futures.workspace = true
gazebo.workspace = true
itertools.workspace = true
os_str_bytes.workspace = true
regex.workspace = true
serde_json.workspace = true
siphasher.workspace = true
starlark_map.workspace = true
strong_hash.workspace = true
tokio.workspace = true
yak_artifact.workspace = true
yak_build_api.workspace = true
yak_cli_proto.workspace = true
yak_common.workspace = true
yak_core.workspace = true
yak_data.workspace = true
yak_error.workspace = true
yak_execute.workspace = true
yak_fs.workspace = true
yak_hash.workspace = true
yak_interpreter.workspace = true
yak_node.workspace = true
yak_query.workspace = true
yak_server_ctx.workspace = true
yak_util.workspace = true
zstd.workspace = true

[lints]
workspace = true
