load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "strong_hash",
    srcs = glob(["src/**/*.rs"]),
    features = [
        "compact_str",
        "num-bigint",
        "triomphe",
    ],
    deps = [
        "//gazebo/strong_hash_derive:strong_hash_derive",
        "//third-party/rust:compact_str",
        "//third-party/rust:num-bigint",
        "//third-party/rust:ref-cast",
        "//third-party/rust:triomphe",
    ],
)
