load("//build_defs:rust.bzl", "rust_library")

rust_library(
    name = "buck2_log_common",
    srcs = glob([
        "src/**/*.rs",
    ]),
    deps = [
        "//app/buck2_client_ctx:buck2_client_ctx",
        "//app/buck2_common:buck2_common",
        "//app/buck2_data:buck2_data",
        "//app/buck2_error:buck2_error",
        "//app/buck2_event_log:buck2_event_log",
        "//app/buck2_event_observer:buck2_event_observer",
        "//app/buck2_events:buck2_events",
        "//app/buck2_fs:buck2_fs",
        "//app/buck2_hash:buck2_hash",
        "//gazebo/dupe:dupe",
        "//third-party/rust:clap",
        "//third-party/rust:derive_more",
        "//third-party/rust:flate2",
        "//third-party/rust:futures",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:tokio-stream",
    ],
)
