load("//build_defs:rust.bzl", "rust_binary")

rust_binary(
    name = "read_dump",
    srcs = ["src/main.rs"],
    deps = [
        "//dice/dice:dice",
        "//third-party/rust:anyhow",
        "//third-party/rust:bincode",
        "//third-party/rust:clap",
        "//third-party/rust:serde_json",
    ],
)
