load("//build_defs:rust.bzl", "rust_binary", "rust_library")

rust_library(
    name = "three_billion_instructions",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//third-party/rust:thiserror",
    ],
)

rust_binary(
    name = "three_billion_instructions-bin",
    srcs = ["bin/three_billion_instructions.rs"],
    crate_root = "bin/three_billion_instructions.rs",
    deps = [
        ":three_billion_instructions",
    ],
)
